import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProductDetailsFields1774891285373 implements MigrationInterface {
    name = 'AddProductDetailsFields1774891285373'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`product_option_values\` DROP FOREIGN KEY \`product_option_values_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`variant_options\` DROP FOREIGN KEY \`variant_options_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`variant_options\` DROP FOREIGN KEY \`variant_options_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`order_items_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`category_departments\` DROP FOREIGN KEY \`category_departments_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`category_departments\` DROP FOREIGN KEY \`category_departments_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`product_departments\` DROP FOREIGN KEY \`product_departments_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`product_departments\` DROP FOREIGN KEY \`product_departments_ibfk_2\``);
        await queryRunner.query(`DROP INDEX \`slug\` ON \`departments\``);
        await queryRunner.query(`DROP INDEX \`idx_option_values_option\` ON \`product_option_values\``);
        await queryRunner.query(`DROP INDEX \`idx_option_values_position\` ON \`product_option_values\``);
        await queryRunner.query(`DROP INDEX \`idx_product_options_position\` ON \`product_options\``);
        await queryRunner.query(`DROP INDEX \`idx_product_options_product\` ON \`product_options\``);
        await queryRunner.query(`DROP INDEX \`idx_variant_options_value\` ON \`variant_options\``);
        await queryRunner.query(`DROP INDEX \`idx_variant_options_variant\` ON \`variant_options\``);
        await queryRunner.query(`DROP INDEX \`optionId\` ON \`variant_options\``);
        await queryRunner.query(`DROP INDEX \`uk_variant_option\` ON \`variant_options\``);
        await queryRunner.query(`DROP INDEX \`idx_orderId\` ON \`order_items\``);
        await queryRunner.query(`DROP INDEX \`idx_productId\` ON \`order_items\``);
        await queryRunner.query(`DROP INDEX \`idx_orderNumber\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`idx_status\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`idx_userId\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`orderNumber\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`idx_productId\` ON \`wishlists\``);
        await queryRunner.query(`DROP INDEX \`idx_userId\` ON \`wishlists\``);
        await queryRunner.query(`DROP INDEX \`unique_user_product\` ON \`wishlists\``);
        await queryRunner.query(`DROP INDEX \`slug\` ON \`brands\``);
        await queryRunner.query(`DROP INDEX \`departmentId\` ON \`category_departments\``);
        await queryRunner.query(`DROP INDEX \`departmentId\` ON \`product_departments\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`features\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`keySpecifications\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`packaging\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`directionToUse\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`additionalInfo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`warranty\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD UNIQUE INDEX \`IDX_a23b1fdc69006219d8acc76c04\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`sortOrder\` \`sortOrder\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`parentId\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`parentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` CHANGE \`position\` \`position\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_options\` CHANGE \`position\` \`position\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`product_options\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_options\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`variant_options\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`sku\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`price\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`price\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`packQuantity\` \`packQuantity\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`variantKey\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`variantKey\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`inventory\` ADD \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP COLUMN \`city\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD \`city\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP COLUMN \`state\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD \`state\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP COLUMN \`country\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD \`country\` varchar(255) NOT NULL DEFAULT 'India'`);
        await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`isDefault\` \`isDefault\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`orderId\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`orderId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`productVariantId\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`productVariantId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`productImage\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`productImage\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`sku\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`price\` \`price\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`sellingPrice\` \`sellingPrice\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`taxAmount\` \`taxAmount\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`discountAmount\` \`discountAmount\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`totalAmount\` \`totalAmount\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`status\` varchar(255) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`shipments\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD \`status\` varchar(255) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP COLUMN \`carrier\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD \`carrier\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`orderNumber\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`orderNumber\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD UNIQUE INDEX \`IDX_59b0c3b34ea0fa5562342f2414\` (\`orderNumber\`)`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`userId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`status\` varchar(255) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`couponCode\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`couponCode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`couponDiscount\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`couponDiscount\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`shippingAddressId\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`shippingAddressId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`billingAddressId\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`billingAddressId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`customerNote\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`customerNote\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`adminNote\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`adminNote\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`DROP INDEX \`IDX_0c82053edd6612e8c21cb0abcd\` ON \`cart\``);
        await queryRunner.query(`ALTER TABLE \`cart\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`cart\` ADD \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD \`userId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` (\`phone\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`productId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD UNIQUE INDEX \`IDX_b15428f362be2200922952dc26\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`logo\``);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`sortOrder\` \`sortOrder\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`sku\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`price\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`brand\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`brand\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`images\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`images\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`categoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`hasVariants\` \`hasVariants\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`banners\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`banners\` ADD \`image\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`banners\` DROP COLUMN \`link\``);
        await queryRunner.query(`ALTER TABLE \`banners\` ADD \`link\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`banners\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`banners\` CHANGE \`sortOrder\` \`sortOrder\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`banners\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`banners\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_0c82053edd6612e8c21cb0abcd\` ON \`cart\` (\`userId\`, \`productId\`, \`productVariantId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e039df3c52d27620a4ed541d57\` ON \`category_departments\` (\`departmentId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0c28eaac5e62ce1d80e7ce987b\` ON \`category_departments\` (\`categoryId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f2988b13bdf257196e9db434a9\` ON \`product_departments\` (\`departmentId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e2bc97b9cc49f2a731e0781dc6\` ON \`product_departments\` (\`productId\`)`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_9a6f051e66982b5f0318981bcaa\` FOREIGN KEY (\`parentId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` ADD CONSTRAINT \`FK_194c98d26740b931df39c29ac1c\` FOREIGN KEY (\`optionId\`) REFERENCES \`product_options\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_options\` ADD CONSTRAINT \`FK_96d8f73d05e681974c07b99ee5d\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_options\` ADD CONSTRAINT \`FK_0d575dfc2a1f96f58098fd96f80\` FOREIGN KEY (\`variantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_options\` ADD CONSTRAINT \`FK_48fb0a885ff3e3e368d8cb63c0c\` FOREIGN KEY (\`optionId\`) REFERENCES \`product_options\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_options\` ADD CONSTRAINT \`FK_9bc663758f2e2677691cb090bb6\` FOREIGN KEY (\`optionValueId\`) REFERENCES \`product_option_values\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_f515690c571a03400a9876600b5\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory\` ADD CONSTRAINT \`FK_c8622e1e24c6d054d36e8824490\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_95c93a584de49f0b0e13f753630\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_cdb99c05982d5191ac8465ac010\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_af929a5f2a400fdb6913b4967e1\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD CONSTRAINT \`FK_13ba957bcb616719a0dc3fca82f\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart\` ADD CONSTRAINT \`FK_756f53ab9466eb52a52619ee019\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart\` ADD CONSTRAINT \`FK_371eb56ecc4104c2644711fa85f\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart\` ADD CONSTRAINT \`FK_ae0857e0acd7f190bbef3a86fb5\` FOREIGN KEY (\`productVariantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_4f3c30555daa6ab0b70a1db772c\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_063c6f46d6cbebf35f3a5ec3d4e\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_7ed5659e7139fc8bc039198cc1f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_a6b3c434392f5d10ec171043666\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ea86d0c514c4ecbb5694cbf57df\` FOREIGN KEY (\`brandId\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ff56834e735fa78a15d0cf21926\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_departments\` ADD CONSTRAINT \`FK_e039df3c52d27620a4ed541d57d\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`category_departments\` ADD CONSTRAINT \`FK_0c28eaac5e62ce1d80e7ce987b7\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_departments\` ADD CONSTRAINT \`FK_f2988b13bdf257196e9db434a9f\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`product_departments\` ADD CONSTRAINT \`FK_e2bc97b9cc49f2a731e0781dc62\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`product_departments\` DROP FOREIGN KEY \`FK_e2bc97b9cc49f2a731e0781dc62\``);
        await queryRunner.query(`ALTER TABLE \`product_departments\` DROP FOREIGN KEY \`FK_f2988b13bdf257196e9db434a9f\``);
        await queryRunner.query(`ALTER TABLE \`category_departments\` DROP FOREIGN KEY \`FK_0c28eaac5e62ce1d80e7ce987b7\``);
        await queryRunner.query(`ALTER TABLE \`category_departments\` DROP FOREIGN KEY \`FK_e039df3c52d27620a4ed541d57d\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ff56834e735fa78a15d0cf21926\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ea86d0c514c4ecbb5694cbf57df\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_a6b3c434392f5d10ec171043666\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_7ed5659e7139fc8bc039198cc1f\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_063c6f46d6cbebf35f3a5ec3d4e\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_4f3c30555daa6ab0b70a1db772c\``);
        await queryRunner.query(`ALTER TABLE \`cart\` DROP FOREIGN KEY \`FK_ae0857e0acd7f190bbef3a86fb5\``);
        await queryRunner.query(`ALTER TABLE \`cart\` DROP FOREIGN KEY \`FK_371eb56ecc4104c2644711fa85f\``);
        await queryRunner.query(`ALTER TABLE \`cart\` DROP FOREIGN KEY \`FK_756f53ab9466eb52a52619ee019\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP FOREIGN KEY \`FK_13ba957bcb616719a0dc3fca82f\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_af929a5f2a400fdb6913b4967e1\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_cdb99c05982d5191ac8465ac010\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY \`FK_95c93a584de49f0b0e13f753630\``);
        await queryRunner.query(`ALTER TABLE \`inventory\` DROP FOREIGN KEY \`FK_c8622e1e24c6d054d36e8824490\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_f515690c571a03400a9876600b5\``);
        await queryRunner.query(`ALTER TABLE \`variant_options\` DROP FOREIGN KEY \`FK_9bc663758f2e2677691cb090bb6\``);
        await queryRunner.query(`ALTER TABLE \`variant_options\` DROP FOREIGN KEY \`FK_48fb0a885ff3e3e368d8cb63c0c\``);
        await queryRunner.query(`ALTER TABLE \`variant_options\` DROP FOREIGN KEY \`FK_0d575dfc2a1f96f58098fd96f80\``);
        await queryRunner.query(`ALTER TABLE \`product_options\` DROP FOREIGN KEY \`FK_96d8f73d05e681974c07b99ee5d\``);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` DROP FOREIGN KEY \`FK_194c98d26740b931df39c29ac1c\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_9a6f051e66982b5f0318981bcaa\``);
        await queryRunner.query(`DROP INDEX \`IDX_e2bc97b9cc49f2a731e0781dc6\` ON \`product_departments\``);
        await queryRunner.query(`DROP INDEX \`IDX_f2988b13bdf257196e9db434a9\` ON \`product_departments\``);
        await queryRunner.query(`DROP INDEX \`IDX_0c28eaac5e62ce1d80e7ce987b\` ON \`category_departments\``);
        await queryRunner.query(`DROP INDEX \`IDX_e039df3c52d27620a4ed541d57\` ON \`category_departments\``);
        await queryRunner.query(`DROP INDEX \`IDX_0c82053edd6612e8c21cb0abcd\` ON \`cart\``);
        await queryRunner.query(`ALTER TABLE \`banners\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`banners\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`banners\` CHANGE \`sortOrder\` \`sortOrder\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`banners\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`banners\` DROP COLUMN \`link\``);
        await queryRunner.query(`ALTER TABLE \`banners\` ADD \`link\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`banners\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`banners\` ADD \`image\` varchar(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`hasVariants\` \`hasVariants\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`categoryId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`images\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`images\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`brand\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`brand\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`price\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price\` decimal NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`sku\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`sortOrder\` \`sortOrder\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`logo\``);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`logo\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP INDEX \`IDX_b15428f362be2200922952dc26\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`productId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_a000cca60bcf04454e72769949\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD \`userId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`cart\` ADD \`productId\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_0c82053edd6612e8c21cb0abcd\` ON \`cart\` (\`userId\`, \`productId\`, \`productVariantId\`)`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`adminNote\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`adminNote\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`customerNote\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`customerNote\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`billingAddressId\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`billingAddressId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`shippingAddressId\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`shippingAddressId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`couponDiscount\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`couponDiscount\` decimal NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`couponCode\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`couponCode\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`status\` varchar(20) NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`userId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP INDEX \`IDX_59b0c3b34ea0fa5562342f2414\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`orderNumber\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`orderNumber\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP COLUMN \`carrier\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD \`carrier\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD \`status\` enum ('pending', 'shipped', 'in_transit', 'delivered', 'returned') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`shipments\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`status\` varchar(50) NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`id\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`totalAmount\` \`totalAmount\` decimal(10,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`discountAmount\` \`discountAmount\` decimal(10,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`taxAmount\` \`taxAmount\` decimal(10,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`sellingPrice\` \`sellingPrice\` decimal(10,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`price\` \`price\` decimal(10,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`sku\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`productImage\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`productImage\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`productVariantId\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`productVariantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`productId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP COLUMN \`orderId\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD \`orderId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`isDefault\` \`isDefault\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP COLUMN \`country\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD \`country\` varchar(100) NULL DEFAULT 'India'`);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP COLUMN \`state\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD \`state\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP COLUMN \`city\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD \`city\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`inventory\` ADD \`productId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`variantKey\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`variantKey\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`packQuantity\` \`packQuantity\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`price\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`price\` decimal NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`sku\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`sku\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP COLUMN \`productId\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD \`productId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`variant_options\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`product_options\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`product_options\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`product_options\` CHANGE \`position\` \`position\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` CHANGE \`position\` \`position\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`parentId\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`parentId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`name\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`sortOrder\` \`sortOrder\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`departments\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD \`image\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP INDEX \`IDX_a23b1fdc69006219d8acc76c04\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`warranty\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`additionalInfo\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`directionToUse\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`packaging\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`keySpecifications\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`features\``);
        await queryRunner.query(`CREATE INDEX \`departmentId\` ON \`product_departments\` (\`departmentId\`)`);
        await queryRunner.query(`CREATE INDEX \`departmentId\` ON \`category_departments\` (\`departmentId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`slug\` ON \`brands\` (\`slug\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_user_product\` ON \`wishlists\` (\`userId\`, \`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_userId\` ON \`wishlists\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_productId\` ON \`wishlists\` (\`productId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`orderNumber\` ON \`orders\` (\`orderNumber\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_userId\` ON \`orders\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_status\` ON \`orders\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_orderNumber\` ON \`orders\` (\`orderNumber\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_productId\` ON \`order_items\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_orderId\` ON \`order_items\` (\`orderId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uk_variant_option\` ON \`variant_options\` (\`variantId\`, \`optionId\`)`);
        await queryRunner.query(`CREATE INDEX \`optionId\` ON \`variant_options\` (\`optionId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_variant_options_variant\` ON \`variant_options\` (\`variantId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_variant_options_value\` ON \`variant_options\` (\`optionValueId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_options_product\` ON \`product_options\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_options_position\` ON \`product_options\` (\`productId\`, \`position\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_option_values_position\` ON \`product_option_values\` (\`optionId\`, \`position\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_option_values_option\` ON \`product_option_values\` (\`optionId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`slug\` ON \`departments\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`product_departments\` ADD CONSTRAINT \`product_departments_ibfk_2\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_departments\` ADD CONSTRAINT \`product_departments_ibfk_1\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_departments\` ADD CONSTRAINT \`category_departments_ibfk_2\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category_departments\` ADD CONSTRAINT \`category_departments_ibfk_1\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`order_items_ibfk_1\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_options\` ADD CONSTRAINT \`variant_options_ibfk_2\` FOREIGN KEY (\`optionValueId\`) REFERENCES \`product_option_values\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`variant_options\` ADD CONSTRAINT \`variant_options_ibfk_1\` FOREIGN KEY (\`optionId\`) REFERENCES \`product_options\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_option_values\` ADD CONSTRAINT \`product_option_values_ibfk_1\` FOREIGN KEY (\`optionId\`) REFERENCES \`product_options\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
