export const STATE_DENTAL_COUNCILS = [
  'Andhra Pradesh State Dental Council',
  'Arunachal Pradesh State Dental Council',
  'Assam State Dental Council',
  'Bihar State Dental Council',
  'Chhatisgarh State Dental Council',
  'Dental Council of Chandigarh',
  'Delhi State Dental Council',
  'Goa State Dental Council',
  'Gujarat State Dental Council',
  'Haryana State Dental Council',
  'Himachal Pradesh State Dental Council',
  'Jharkhand State Dental Council',
  'J & K State Dental Council',
  'Karnataka State Dental Council',
  'Kerala State Dental Council',
  'Madhya Pradesh State Dental Council',
  'Maharashtra State Dental Council',
  'Meghalaya State Dental Council',
  'Mizoram State Registration Tribunal',
  'Manipur State Dental Council',
  'Nagaland State Dental Council',
  'Orissa State Dental Council',
  'State Dental Council, Puducherry',
  'Punjab State Dental Council',
  'Rajasthan State Dental Council',
  'Sikkim Dental Registration Tribunal',
  'Tamil Nadu State Dental Council',
  'Tripura State Dental Council',
  'Telangana Dental Council',
  'Uttar Pradesh State Dental Council',
  'Uttarakhand Dentists Registration Tribunals',
  'West Bengal State Dental Council',
] as const;

export const STATE_COUNCIL_MAP: Record<string, string> = {
  'Andhra Pradesh State Dental Council': 'AND',
  'Arunachal Pradesh State Dental Council': 'ARN',
  'Assam State Dental Council': 'ASS',
  'Bihar State Dental Council': 'BIH',
  'Chhatisgarh State Dental Council': 'CHA',
  'Dental Council of Chandigarh': 'CHG',
  'Delhi State Dental Council': 'DEL',
  'Goa State Dental Council': 'GOA',
  'Gujarat State Dental Council': 'GUJ',
  'Haryana State Dental Council': 'HAR',
  'Himachal Pradesh State Dental Council': 'HP',
  'Jharkhand State Dental Council': 'JHA',
  'J & K State Dental Council': 'JK',
  'Karnataka State Dental Council': 'KAR',
  'Kerala State Dental Council': 'KER',
  'Madhya Pradesh State Dental Council': 'MAD',
  'Maharashtra State Dental Council': 'MAH',
  'Meghalaya State Dental Council': 'MEG',
  'Mizoram State Registration Tribunal': 'MIZ',
  'Manipur State Dental Council': 'MS',
  'Nagaland State Dental Council': 'NS',
  'Orissa State Dental Council': 'ORI',
  'State Dental Council, Puducherry': 'PON',
  'Punjab State Dental Council': 'PUN',
  'Rajasthan State Dental Council': 'RAJ',
  'Sikkim Dental Registration Tribunal': 'SKM',
  'Tamil Nadu State Dental Council': 'TAM',
  'Tripura State Dental Council': 'TRI',
  'Telangana Dental Council': 'TS',
  'Uttar Pradesh State Dental Council': 'UP',
  'Uttarakhand Dentists Registration Tribunals': 'UTR',
  'West Bengal State Dental Council': 'WES',
};
